// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'category',
      label: '⚙️ Installation',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'installation'}],
    },
    {
      type: 'category',
      label: '🚀 Getting Started',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'getting-started'}],
    },
    {
      type: 'category', 
      label: '📚 Basics',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'basics'}],
    },
    {
      type: 'category',
      label: '🔧 Technical Details',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'technical-details'}],
    },
    {
      type: 'category',
      label: '💻 CLI',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'cli'}],
    },
    {
      type: 'category',
      label: '📖 Resources',
      className: 'sidebar-icon',
      items: [{type: 'autogenerated', dirName: 'resources'}],
    },
  ],
  apiSidebar: [
    {
      type: 'autogenerated',
      dirName: 'api-reference',
    },
  ],
};

export default sidebars;
